export const authRouts = {
  me: '/auth/me',
  login: '/auth/login',
  registration: '/auth/registration',
  registrationСonfirm: '/auth/registration-confirmation',
  registrationEmailResend: '/auth/registration-email-resending',
  forgotPassword: '/auth/forgot-password',
  passwordRecover: '/auth/password-recovery',
  newPasswordCreate: '/auth/new-password',
  recoveryCodeCheck: '/auth/check-recovery-code',
  success: '/auth/success',
  failed: '/auth/failed',
  failedPasswordRecovery: '/auth/failed-recovery',
  successPasswordRecovery: '/auth/success-recovery',
  logout: '/auth/logout',
}
